export const INPUT_TEXT = "INPUT_TEXT"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const COMENT_CREATE = 'COMENT_CREATE'
export const COMENT_DELETE = 'COMENT_DELETE'